# Releases https://github.com/external-secrets/external-secrets/releases?q=&expanded=true
installCRDs: true

image:
  repository: ghcr.io/external-secrets/external-secrets
  tag: v1.1.0

certController:
  image:
    repository: ghcr.io/external-secrets/external-secrets
    tag: v1.1.0

webhook:
  image:
    repository: ghcr.io/external-secrets/external-secrets
    tag: v1.1.0
