apiVersion: external-secrets.io/v1
kind: ClusterSecretStore
metadata:
  name: infisical-cluster-secret-store-sandbox
spec:
  provider:
    infisical:
      secretsScope:
        environmentSlug: "sandbox"
        secretsPath: "/"
        projectSlug: "dffa021f-4672-4fb1-a321-dc9255d80936"
        recursive: true
      auth:
        tokenAuthCredentials:
          accessToken:
            name: infisical-api-token
            key: token
            namespace: external-secrets
      hostAPI: "http://infisical-infisical.infisical.svc.cluster.local:8080"
